### ISSUE TITLE
Same issue as arkiran

### ISSUE THREAD

**Issue by gregfarquhar** [Azure-Samples/active-directory-dotnet-graphapi-console#4]
I get an exception at the second part of the app, after a request for my credentials.

An unhandled exception of type 'Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException' occurred in Microsoft.IdentityModel.Clients.ActiveDirectory.dll

Additional information: AADSTS90014: The request body must contain the following parameter: 'client_secret or client_assertion'.

**Comment by Injac** [comment]
I would like to see this issues re-opened. And to have a better documentation for developers and not system integrators, Architects or consultants. The differences between native vs. web-apps need to be documented more clearly. And this could be done for every new release of the graph-apis and for ADAL. It's frustrating to try for hours without any success.
