### ISSUE TITLE
Insufficient privileges to complete the operation

### ISSUE THREAD

**Issue by anit05** [Azure-Samples/active-directory-dotnet-graphapi-console#48]
Hi
I am https://graphexplorer.azurewebsites.net/ and I have logged in with user having directory role as global administrator in my Azure AD b2c directory.

I have registered an app there and provide it Direcory reaad and write persmissions in Application permission section.Below is screenshot of permissions configured.
I am using https://graph.windows.net/me with api_version=1.6 to partially update the user
say 

{
	"displayName": "new display name"	
}

But it returns with error

{
    "odata.error": {
        "code": "Authorization_RequestDenied",
        "message": {
            "lang": "en",
            "value": "Insufficient privileges to complete the operation."
        }
    }
}

It is working with B2C console app i have downloaded from their repository and configured with my registered app settings.

![app-permisisons](https://cloud.githubusercontent.com/assets/6780356/25943266/f674a6e0-365c-11e7-9253-44d5f2ef9772.png)

What i am missing here ?

**Comment by jbartolome** [comment]
Hello,
I've setup the permissions to the application as follows:
![image](https://user-images.githubusercontent.com/19414037/30435792-80cd8da0-991f-11e7-9f62-a9ac48220e5d.png)

That worked in my situation, but I wasn't using the B2C sample, rather, the dotnet-webapi version. It should be of similar delegated permissions, though, so try it out. I hope it helps!

**Comment by jmprieur** [comment]
Closing as there is a reply
