### ISSUE TITLE
User delete async result  "Insufficient privileges to complete the operation."

### ISSUE THREAD

**Issue by duongthaiha** [Azure-Samples/active-directory-dotnet-graphapi-console#5]
Hi I tried to example however i receive "Insufficient privileges to complete the operation."
I have set the the web application to have different type of permission even to have all of them(both read and write directory data). I can create user however can not delete the user. Any help is much appreciated.  The code is original from the example 

 //*********************************************************************************************
            // Delete the user that we just created
            //*********************************************************************************************
            if (userToBeAdded.ObjectId != null)
            {
                try
                {
                    userToBeAdded.DeleteAsync().Wait();
                    Console.WriteLine("\nUser {0} was deleted", userToBeAdded.DisplayName);
                }
                catch (Exception e)
                {
                    Console.WriteLine("Deleting User failed {0} {1}", e.Message,
                        e.InnerException != null ? e.InnerException.Message : "");
                }
            }
            if (newUser.ObjectId != null)
            {
                try
                {
                    newUser.DeleteAsync().Wait();
                    Console.WriteLine("\nUser {0} was deleted", newUser.DisplayName);
                }
                catch (Exception e)
                {
                    Console.WriteLine("Deleting User failed {0} {1}", e.Message,
                        e.InnerException != null ? e.InnerException.Message : "");
                }
            }

**Comment by vsix27** [comment]
first option (use Add-MsolRoleMember to add it to “Company Administrator” role) worked for me - specifically - 
1. get clientif of your web application - can do it in azure web/configuration, or in PowerShell when run
# 1. list all principals, you web app probably will be  last...
Get-MsolServicePrincipal | ft DisplayName, AppPrincipalId -AutoSize

2. run
# 2. put your web app guid [this is ClientIdWebApp] and use it to get MsolServicePrincipal
$ClientIdWebApp = '5dc390de-1a63-4377-b16e-f4d0ddd9d921'
$webApp = Get-MsolServicePrincipal –AppPrincipalId $ClientIdWebApp

# 3. use Add-MsolRoleMember to add it to “Company Administrator” role).
Add-MsolRoleMember -RoleName "Company Administrator" -RoleMemberType ServicePrincipal -RoleMemberObjectId $webApp.ObjectId
