### ISSUE TITLE
AssignedLicense 

### ISSUE THREAD

**Issue by icardosos** [Azure-Samples/active-directory-dotnet-graphapi-console#8]
Hi,
I'm trying to add some license to my user, but I always get this message.

Open navigation properties are not supported on OpenTypes. Property name: 'DirectoryDataService.assignLicense'.

AssignedLicense addLicense = new AssignedLicense
            {
                SkuId = new Guid("some guid")
            };
IList<AssignedLicense> licensesToAdd = new[] { addLicense };
IList<Guid> licensesToRemove = new Guid[] { };

 var retrievedUsers = activeDirectoryClient.Users
               .Where(user => user.UserPrincipalName.Equals("some user"))
               .ExecuteAsync().Result.CurrentPage.First();
retrievedUsers.AssignLicenseAsync(licensesToAdd, licensesToRemove).Wait();

Have any idea what's wrong ?

Tks

**Comment by dkershaw10** [comment]
Believe this is fixed in later versions

**Comment by jkovach82** [comment]
ICollection<AssignedLicense> addLicense = new List<AssignedLicense>();
AssignedLicense assignedLicense = new AssignedLicense
{
SkuId = skuId.Key.ToGuid()
};
addLicense.Add(assignedLicense);
user.AssignLicenseAsync(addLicense, null).Wait();
